In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")
df.head(1)

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               4852 non-null   str
 1   industry                  4760 non-null   str
 2   employment_status         4806 non-null   str
 3   location                  4792 non-null   str
 4   annual_income             4631 non-null   float64
 5   number_of_courses_viewed  5000 non-null   int64
 6   interaction_count         5000 non-null   int64
 7   lead_score                4965 non-null   float64
 8   converted                 5000 non-null   int64
dtypes: float64(2), int64(3), str(4)
memory usage: 351.7 KB

In [5]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [13]:
categorical_columns = list(df.columns[df.dtypes == "str"])
numerical_columns = list(df.columns[df.dtypes != "str"])

In [14]:
for column in df.columns:
    if column in categorical_columns:
        df[column] = df[column].fillna("NA")
    elif column in numerical_columns:
        df[column] = df[column].fillna(0)

In [15]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Question 1

In [16]:
df.industry.value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

### Question 2

In [ ]:
df[numerical_columns].corr()

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
annual_income,1.000000,0.161300,0.122842,0.229496,0.189652
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204,0.395038
interaction_count,0.122842,0.721609,1.000000,0.915746,0.448624
lead_score,0.229496,0.757204,0.915746,1.000000,0.483246
converted,0.189652,0.395038,0.448624,0.483246,1.000000

In [ ]:
import seaborn as sns

import matplotlib.pyplot as plt

sns.heatmap(df[numerical_columns].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.show()